logging:
  level:
    org:
      springframework: ERROR
server:
  port: 9000
spring:
  application:
    name: api-auth
  datasource:
    password: ''
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
  main:
    banner-mode: 'off'

jwt:
   secret: 1234
   expiration: 604800
   
   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka