logging:
  level:
    org:
      springframework: ERROR
server:
  port: 9000
spring:
  application:
    name: auth
  datasource:
    password: ''
    url: ${DB_URL}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: none
  main:
    banner-mode: 'off'

jwt:
   secret: ${JWT_SECRET}
   expiration: 604800